development:
  admin_name: Nathaniel Turner
  admin_email: <%= ENV["GMAIL"] %>
  admin_password: <%= ENV["GMAILPASSWORD"] %>
  domain_name: example.com
  secret_key_base: 3eb93bf2b5a577e83db319c5881b84423ba381c776c96049244414834c311fcd61887e37656a98d63bf8620ebd62c295709c3f34603cd30b0dff933af94612ad

test:
  domain_name: example.com
  secret_key_base: 1dee91cbc1b0e70dde8de70df0ffd853143fed615e62f61118bf20019650fe24956082e4568e789850b4925abbe0b6d0b3e9c26211c7c9309d722e40f382f639

production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
